name: Linux

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  CPU_CORES: 2

jobs:
  build:
    name: Build on Linux
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc gcc-multilib g++ g++-multilib

      - name: Build using CMake
        run: |
          cmake --preset linux-unit-tests
          cmake --build --preset linux-unit-tests --parallel ${{ env.CPU_CORES }}

      - name: Run unit tests
        run: ctest --preset linux-all --parallel ${{ env.CPU_CORES }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rehldsm-linux
          path: bin/
